name: cocoapods-integration

on:
  pull_request:
    paths:
    - 'CocoapodsIntegrationTest/**'
    - '.github/workflows/cocoapods-integration.yml'
    - 'Gemfile*'
  schedule:
    # Run every day at 2am (PST) - cron uses UTC times
    - cron:  '0 10 * * *'

jobs:
  tests:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'

    runs-on: macos-11
    strategy:
      matrix:
        config: [Cocoapods_multiprojects_frameworks]
    steps:
    - uses: actions/checkout@v2
    - uses: mikehardy/buildcache-action@50738c6c77de7f34e66b870e4f8ede333b69d077
      with:
        cache_key: ${{ matrix.os }}
    - name: Get realpath
      run: brew install coreutils
    - name: Build and test
      run: |
        scripts/third_party/travis/retry.sh ./CocoapodsIntegrationTest/scripts/build_with_environment.sh \
          --gemfile=./CocoapodsIntegrationTest/TestEnvironments/${{ matrix.config }}/Gemfile \
          --podfile=./CocoapodsIntegrationTest/TestEnvironments/${{ matrix.config }}/Podfile
