name: database

on:
  pull_request:
    paths:
    - 'FirebaseDatabase**'
    - 'Firebase/Database/**'
    - 'Example/Database/**'
    - 'Interop/Auth/Public/*.h'
    - '.github/workflows/database.yml'
    - 'Gemfile'
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  unit:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macos-latest
    strategy:
      matrix:
        target: [iOS, tvOS, macOS]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: BuildAndTest # can be replaced with pod lib lint with CocoaPods 1.10
      run: scripts/third_party/travis/retry.sh scripts/build.sh Database ${{ matrix.target }} unit
    - name: PrintOutCoverate
      run: |
              gem install slather
              slather coverage -s --scheme FirebaseDatabase-Unit-unit --verbose --workspace ./gen/FirebaseDatabase/FirebaseDatabase.xcworkspace ./gen/FirebaseDatabase/Pods/Pods.xcodeproj

  integration:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: IntegrationTest
      # Only iOS to mitigate flakes.
      run: scripts/third_party/travis/retry.sh scripts/build.sh Database iOS integration
    - name: PrintOutCoverate
      run: |
              gem install slather
              slather coverage -s --scheme "FirebaseDatabase-Unit-integration" --verbose --workspace ./gen/FirebaseDatabase/FirebaseDatabase.xcworkspace ./gen/FirebaseDatabase/Pods/Pods.xcodeproj

  spm:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: iOS Unit Tests
      run: scripts/third_party/travis/retry.sh ./scripts/build.sh DatabaseUnit iOS spm

  spm-cron:
    # Don't run on private repo.
    if: github.event_name == 'schedule' && github.repository == 'Firebase/firebase-ios-sdk'
    runs-on: macOS-latest
    strategy:
      matrix:
        target: [tvOS, macOS, catalyst]
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: Unit Tests
      run: scripts/third_party/travis/retry.sh ./scripts/build.sh DatabaseUnit ${{ matrix.target }} spm

  catalyst:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Setup project and Build for Catalyst
      # Only build the unit tests on Catalyst. Test stopped working when GHA moved to Xcode 11.4.1.
      run: scripts/test_catalyst.sh FirebaseDatabase build FirebaseDatabase-Unit-unit

# Restore when FirebaseUI works with Firebase 7 (#6646)
  quickstart:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    env:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
      signin_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup quickstart
      run: scripts/setup_quickstart.sh database
    - name: Install Secret GoogleService-Info.plist
      run: scripts/decrypt_gha_secret.sh scripts/gha-encrypted/qs-database.plist.gpg \
          quickstart-ios/database/GoogleService-Info.plist "$plist_secret"
    - name: Install Secret FIREGSignInInfo.h
      run: scripts/decrypt_gha_secret.sh scripts/gha-encrypted/FIREGSignInInfo.h.gpg \
          quickstart-ios/TestUtils/FIREGSignInInfo.h "$signin_secret"
    - name: Test objc quickstart
      run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart.sh Database)
    - name: Test swift quickstart
      run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart.sh Database swift)

  pod-lib-lint:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [ios, tvos, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Build and test
      run: |
        if ( ! -d "/Users/runner/Library/Developer/Xcode/DerivedData" ) then
          rm -r /Users/runner/Library/Developer/Xcode/DerivedData/*
        endif
        scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseDatabase.podspec --platforms=${{ matrix.target }} --verbose --test-specs=unit
        find /Users/runner/Library/Developer/Xcode/DerivedData -regex ".*/.*\.xcresult" -exec xcrun xccov view --report {} \;

  database-cron-only:
    # Don't run on private repo.
    if: github.event_name == 'schedule' && github.repository == 'Firebase/firebase-ios-sdk'
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ios, tvos, macos]
        flags: [
          '--skip-tests --use-static-frameworks',
          '--skip-tests --use-libraries'
        ]
    needs: pod-lib-lint
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: PodLibLint database Cron
      run: |
              scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseDatabase.podspec --platforms=${{ matrix.target }} ${{ matrix.flags }}
              find /Users/runner/Library/Developer/Xcode/DerivedData -regex ".*/.*\.xcresult"
