name: database

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseDatabase**'
    - 'Firebase/Database/**'
    - 'FirebaseSharedSwift**'
    - 'Example/Database/**'
    - 'FirebaseAuth/Interop/*.h'
    - '.github/workflows/database.yml'
    - '.github/workflows/common.yml'
    - '.github/workflows/common_cocoapods.yml'
    - '.github/workflows/common_catalyst.yml'
    - '.github/workflows/common_quickstart.yml'
    - '.github/workflows/common_cocoapods_cron.yml'
    - 'Gemfile*'
    - 'scripts/run_database_emulator.sh'
  schedule:
    # Run every day at 3am (PDT) / 6am (EDT) - cron uses UTC times
    - cron:  '0 10 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  spm:
    strategy:
      matrix:
        target: [DatabaseUnit, DatabaseUnitSwift]
    uses: ./.github/workflows/common.yml
    with:
      target: ${{  matrix.target }}

  catalyst:
    uses: ./.github/workflows/common_catalyst.yml
    with:
      product: FirebaseDatabase
      target: FirebaseDatabase-Unit-unit

  pod_lib_lint:
    uses: ./.github/workflows/common_cocoapods.yml
    with:
      product: FirebaseDatabase
      test_specs: unit
      buildonly_platforms: macOS

  integration:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - uses: mikehardy/buildcache-action@c87cea0ccd718971d6cc39e672c4f26815b6c126
      with:
        cache_key: integration${{ matrix.os }}
    - uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Install xcpretty
      run: gem install xcpretty
    - name: Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    - name: IntegrationTest
      # Only iOS to mitigate flakes.
      run: scripts/third_party/travis/retry.sh scripts/build.sh Database iOS integration

  quickstart:
    uses: ./.github/workflows/common_quickstart.yml
    with:
      product: Database
      setup_command: scripts/setup_quickstart_spm.sh database
      plist_src_path: scripts/gha-encrypted/qs-database.plist.gpg
      plist_dst_path: quickstart-ios/database/GoogleService-Info.plist
      run_tests: false
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}

  database-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/common_cocoapods_cron.yml
    with:
      product: FirebaseDatabase
      platforms: '[ "ios", "tvos", "macos" ]'
      flags: '[ "--skip-tests --use-static-frameworks" ]'
