name: datatransport

on:
  pull_request:
    paths:
    - 'GoogleDataTransport**'
    - 'GoogleDataTransportCCTSupport**'
    - '.github/workflows/datatransport.yml'
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  datatransport-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh
    - name: PodLibLint iOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=ios
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=ios

  datatransport-macosos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh
    - name: PodLibLint macOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=macos
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=macos

  datatransport-tvos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh
    - name: PodLibLint tvOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=tvos
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=tvos

# Scheduled jobs

  datatransport-use-libraries:
    runs-on: macos-latest
    if: github.event_name == 'schedule'
    needs: [datatransport-ios, datatransport-macos, datatransport-tvos]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh
    - name: PodLibLint iOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=ios --use-libraries
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=ios --use-libraries
    - name: PodLibLint macOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=macos --use-libraries
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=macos --use-libraries
    - name: PodLibLint tvOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=tvos --use-libraries
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=tvos --use-libraries

  datatransport-use-modular-headers:
    runs-on: macos-latest
    if: github.event_name == 'schedule'
    needs: [datatransport-ios, datatransport-macos, datatransport-tvos]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh
    - name: PodLibLint iOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=ios --use-modular-headers
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=ios --use-modular-headers
    - name: PodLibLint macOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=macos --use-modular-headers
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=macos --use-modular-headers
    - name: PodLibLint tvOS
      run: |
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=tvos --use-modular-headers
        ./scripts/third_party/travis/retry.sh ./scripts/pod_lib_lint.rb GoogleDataTransportCCTSupport.podspec --platforms=tvos --use-modular-headers
