name: generate_issues
on:
  pull_request:
    paths:
    - '.github/workflows/generate_issues.yml'
  schedule:
    # Run every day at 4am (PST) - cron uses UTC times
    - cron:  '0 12 * * *'
jobs:
  generate_an_issue:
    runs-on: ubuntu-latest
    name: Generate a nightly testing report issue
    steps:
    - uses: actions/checkout@v2
    - name: Create a nightly report
      uses: ./.github/actions/testing_report_generation/
      with:
        access-token: '${{ secrets.GITHUB_TOKEN }}'
        exclude-workflow-files: 'performance.yml performance-integration-tests.yml'
