name: infra.samples.symbolcollision

# Tests the Pods listed in SymbolCollisionTest/Podfile for symbol collisions.

on:
  workflow_dispatch:
  pull_request:
    paths:
    - '.github/workflows/infra.samples.symbolcollision.yml'
    - 'SymbolCollisionTest/**'
    - 'Gemfile*'
  schedule:
    # Run every day at 1am (PDT) / 4am (EDT) - cron uses UTC times
    - cron:  '0 8 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  installation-test:
    uses: ./.github/workflows/_build.yml
    with:
      product: SymbolCollision
      platform: iOS
      method: xcodebuild
      setup_command: scripts/install_prereqs.sh SymbolCollision iOS
