name: installations

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseInstallations**'
    - '.github/workflows/installations.yml'
    - '.github/workflows/common.yml'
    - '.github/workflows/common_cocoapods.yml'
    - '.github/workflows/common_catalyst.yml'
    - '.github/workflows/common_quickstart.yml'
    - '.github/workflows/common_cocoapods_cron.yml'
    - 'Gemfile*'
  schedule:
    # Run every day at 11pm (PDT) / 2am (EDT) - cron uses UTC times
    - cron:  '0 6 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  spm:
    uses: ./.github/workflows/common.yml
    with:
      target: FirebaseInstallations
      buildonly_platforms: all

  catalyst:
    uses: ./.github/workflows/common_catalyst.yml
    with:
      product: FirebaseInstallations
      target: FirebaseInstallations-Unit-unit

  pod_lib_lint:
    uses: ./.github/workflows/common_cocoapods.yml
    with:
      product: FirebaseInstallations
      setup_command: |
        scripts/configure_test_keychain.sh
        mkdir -p FirebaseInstallations/Source/Tests/Resources
        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/Installations/GoogleService-Info.plist.gpg \
          FirebaseInstallations/Source/Tests/Resources/GoogleService-Info.plist "$plist_secret"
        echo "FIS_INTEGRATION_TESTS_REQUIRED=1" >> $GITHUB_ENV
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}

  quickstart:
    uses: ./.github/workflows/common_quickstart.yml
    with:
      product: Installations
      setup_command: scripts/setup_quickstart.sh installations
      plist_src_path: scripts/gha-encrypted/Installations/GoogleService-Info.plist.gpg
      plist_dst_path: quickstart-ios/installations/GoogleService-Info.plist
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}

  installations-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/common_cocoapods_cron.yml
    with:
      product: FirebaseInstallations
      platforms: '[ "ios", "tvos", "macos" ]'
      flags: '[ "--use-static-frameworks" ]'
      setup_command: |
        scripts/configure_test_keychain.sh
        mkdir -p FirebaseInstallations/Source/Tests/Resources
        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/Installations/GoogleService-Info.plist.gpg \
          FirebaseInstallations/Source/Tests/Resources/GoogleService-Info.plist "$plist_secret"
        echo "FIS_INTEGRATION_TESTS_REQUIRED=1" >> $GITHUB_ENV
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
