name: sdk.mlmodeldownloader

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseMLModelDownloader**'
    - '.github/workflows/sdk.mlmodeldownloader.yml'
    - '.github/workflows/_common.yml'
    - '.github/workflows/_cocoapods.yml'
    - '.github/workflows/_catalyst.yml'
    - '.github/workflows/_cocoapods.cron.yml'
    - 'Gemfile*'
  schedule:
    # Run every day at 12am (PDT) / 3am (EDT) - cron uses UTC times
    - cron:  '0 7 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  spm:
    uses: ./.github/workflows/_common.yml
    with:
      target: FirebaseMLModelDownloaderUnit

  catalyst:
    uses: ./.github/workflows/_catalyst.yml
    with:
      product: FirebaseMLModelDownloader
      target: FirebaseMLModelDownloader-Unit-unit

  pod_lib_lint:
    uses: ./.github/workflows/_cocoapods.yml
    with:
      product: FirebaseMLModelDownloader
      setup_command: |
        mkdir FirebaseMLModelDownloader/Tests/Integration/Resources
        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/MLModelDownloader/GoogleService-Info.plist.gpg \
          FirebaseMLModelDownloader/Tests/Integration/Resources/GoogleService-Info.plist "$plist_secret"
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}

  mlmodeldownloader-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/_cocoapods.cron.yml
    with:
      product: FirebaseMLModelDownloader
      platforms: '[ "ios", "tvos", "macos" ]'
      flags: '[ "--use-static-frameworks" ]'
      setup_command: |
        scripts/configure_test_keychain.sh
        mkdir FirebaseMLModelDownloader/Tests/Integration/Resources
        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/MLModelDownloader/GoogleService-Info.plist.gpg \
          FirebaseMLModelDownloader/Tests/Integration/Resources/GoogleService-Info.plist "$plist_secret"
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}

  mlmodeldownloader-sample-build-test:
    # Don't run on private repo unless it is a PR.
    if: github.repository == 'Firebase/firebase-ios-sdk' && (github.event_name == 'schedule' || github.event_name == 'pull_request')
    env:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
    runs-on: macos-15
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1
    - name: Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Install simulators in case they are missing.
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
      with:
        timeout_minutes: 15
        max_attempts: 5
        retry_wait_seconds: 120
        command: sudo xcodebuild -downloadPlatform iOS
    - name: Install GoogleService-Info.plist
      run: |
        mkdir FirebaseMLModelDownloader/Apps/Sample/Resources
        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/MLModelDownloader/GoogleService-Info.plist.gpg \
          FirebaseMLModelDownloader/Apps/Sample/Resources/GoogleService-Info.plist "$plist_secret"
    - name: Prereqs
      run: scripts/install_prereqs.sh MLModelDownloaderSample iOS
    - name: Build
      run: ([ -z $plist_secret ] || scripts/build.sh MLModelDownloaderSample iOS)
