name: sdk.inappmessaging

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseInAppMessaging**'
    - 'Interop/Analytics/Public/*.h'
    - '.github/workflows/sdk.inappmessaging.yml'
    - '.github/workflows/_spm.yml'
    - '.github/workflows/_cocoapods.yml'
    - '.github/workflows/_quickstart.yml'
    - '.github/workflows/_cocoapods.cron.yml'
    - 'Gemfile*'
  schedule:
    # Run every day at 11pm (PDT) / 2am (EDT) - cron uses UTC times
    - cron:  '0 6 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  spm:
    uses: ./.github/workflows/_spm.yml
    with:
      target: FirebaseInAppMessaging-Beta
      platforms: iOS
      buildonly_platforms: iOS

  pod_lib_lint:
    uses: ./.github/workflows/_cocoapods.yml
    with:
      product: FirebaseInAppMessaging
      platforms: iOS, tvOS

  tests:
    strategy:
      matrix:
# TODO(#8682): Reenable iPad after fixing Xcode 13 test failures.
#        platform: [iOS, iPad]
        platform: [iOS]
        xcode: [Xcode_16.4]
    uses: ./.github/workflows/_build.yml
    with:
      product: InAppMessaging
      platform: ${{ matrix.platform }}
      method: xcodebuild
      xcode: ${{ matrix.xcode }}
      setup_command: scripts/install_prereqs.sh InAppMessaging ${{ matrix.platform }} xcodebuild

  fiam-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/_cocoapods.cron.yml
    with:
      product: FirebaseInAppMessaging
      platforms: '[ "ios", "tvos" ]'
      flags: '[ "--use-static-frameworks" ]'

  quickstart:
    uses: ./.github/workflows/_quickstart.yml
    with:
      product: InAppMessaging
      setup_command: scripts/setup_quickstart.sh inappmessaging
      plist_src_path: scripts/gha-encrypted/qs-inappmessaging.plist.gpg
      plist_dst_path: quickstart-ios/inappmessaging/GoogleService-Info.plist
      run_tests: false
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
