name: sdk.database

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseDatabase**'
    - 'Firebase/Database/**'
    - 'FirebaseSharedSwift**'
    - 'Example/Database/**'
    - 'FirebaseAuth/Interop/*.h'
    - '.github/workflows/sdk.database.yml'
    - '.github/workflows/_spm.yml'
    - '.github/workflows/_cocoapods.yml'
    - '.github/workflows/_catalyst.yml'
    - '.github/workflows/_quickstart.yml'
    - '.github/workflows/_cocoapods.cron.yml'
    - 'Gemfile*'
    - 'scripts/run_database_emulator.sh'
  schedule:
    # Run every day at 3am (PDT) / 6am (EDT) - cron uses UTC times
    - cron:  '0 10 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  spm:
    strategy:
      matrix:
        target: [DatabaseUnit, DatabaseUnitSwift]
    uses: ./.github/workflows/_spm.yml
    with:
      target: ${{  matrix.target }}

  catalyst:
    uses: ./.github/workflows/_catalyst.yml
    with:
      product: FirebaseDatabase
      target: FirebaseDatabase-Unit-unit

  pod_lib_lint:
    uses: ./.github/workflows/_cocoapods.yml
    with:
      product: FirebaseDatabase
      test_specs: unit
      buildonly_platforms: macOS

  integration:
    uses: ./.github/workflows/_build.yml
    with:
      product: Database
      platform: iOS
      method: integration

  quickstart:
    uses: ./.github/workflows/_quickstart.yml
    with:
      product: Database
      setup_command: scripts/setup_quickstart.sh database
      plist_src_path: scripts/gha-encrypted/qs-database.plist.gpg
      plist_dst_path: quickstart-ios/database/GoogleService-Info.plist
      run_tests: false
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}

  database-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/_cocoapods.cron.yml
    with:
      product: FirebaseDatabase
      platforms: '[ "ios", "tvos", "macos" ]'
      flags: '[ "--skip-tests --use-static-frameworks" ]'
