# Merge the yml file to main branch for the cron job schedule to be effective.
# Reference: https://github.community/t/on-schedule-per-branch/17525
name: sdk.performance.integration

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    # This configuration file.
    - '.github/workflows/sdk.performance.integration.yml'
  # See cron syntax references:
  #   - https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
  #   - https://crontab.guru/
  schedule:
    # Runs once a day.
    - cron:  '0 0 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:

  # Public repository: Build and run the Integration Tests for the Firebase performance E2E Test App.
  performance-integration-tests:
    if: github.event.pull_request.head.repo.fork == false
    uses: ./.github/workflows/_build.yml
    with:
      product: Performance
      platform: all
      method: integration
      setup_command: |
        gem install xcpretty
        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/Performance/GoogleService-Info_e2e_autopush.plist.gpg \
            FirebasePerformance/Tests/FIRPerfE2E/FIRPerfE2EAutopush/GoogleService-Info.plist "$plist_secret"
        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/Performance/GoogleService-Info_e2e_prod.plist.gpg \
            FirebasePerformance/Tests/FIRPerfE2E/FIRPerfE2EProd/GoogleService-Info.plist "$plist_secret"
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
