name: crashlytics

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'Crashlytics**'
    - 'FirebaseCrashlytics.podspec'
    - '.github/workflows/crashlytics.yml'
    - '.github/workflows/common.yml'
    - '.github/workflows/common_cocoapods.yml'
    - '.github/workflows/common_catalyst.yml'
    - '.github/workflows/common_quickstart.yml'
    - '.github/workflows/common_cocoapods_cron.yml'
    - 'Interop/Analytics/Public/*.h'
    - 'Gemfile*'
  schedule:
    # Run every day at 11pm (PDT) / 2am (EDT) - cron uses UTC times
    - cron:  '0 6 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  spm:
    uses: ./.github/workflows/common.yml
    with:
      target: FirebaseCrashlyticsUnit
      is_nightly: ${{ github.event_name == 'schedule' }}

  catalyst:
    uses: ./.github/workflows/common_catalyst.yml
    with:
      product: FirebaseCrashlytics
      target: FirebaseCrashlytics-Unit-unit

  pod_lib_lint:
    uses: ./.github/workflows/common_cocoapods.yml
    with:
      product: FirebaseCrashlytics
      buildonly_platforms: tvOS, macOS, watchOS

  quickstart:
    uses: ./.github/workflows/common_quickstart.yml
    with:
      product: Crashlytics
      setup_command: scripts/setup_quickstart.sh crashlytics
      plist_src_path: scripts/gha-encrypted/qs-crashlytics.plist.gpg
      plist_dst_path: quickstart-ios/crashlytics/GoogleService-Info.plist
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}


  crashlytics-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/common_cocoapods_cron.yml
    with:
      product: FirebaseCrashlytics
      platforms: '[ "ios", "tvos", "macos", "watchos --skip-tests" ]'
      flags: '[ "--use-static-frameworks", "--use-modular-headers --skip-tests" ]'
