name: sdk.abtesting

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseABTesting**'
    - 'Interop/Analytics/Public/*.h'
    - '.github/workflows/sdk.abtesting.yml'
    - '.github/workflows/_spm.yml'
    - '.github/workflows/_cocoapods.yml'
    - '.github/workflows/_catalyst.yml'
    - '.github/workflows/_quickstart.yml'
    - '.github/workflows/_cocoapods.cron.yml'
    - 'Gemfile*'
  schedule:
    # Run every day at 2am (PDT) / 5am (EDT) - cron uses UTC times
    - cron: '0 9 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  spm:
    uses: ./.github/workflows/_spm.yml
    with:
      target: ABTestingUnit

  catalyst:
    uses: ./.github/workflows/_catalyst.yml
    with:
      product: FirebaseABTesting
      target: FirebaseABTesting-Unit-unit

  pod_lib_lint:
    uses: ./.github/workflows/_cocoapods.yml
    with:
      product: FirebaseABTesting

  quickstart:
    uses: ./.github/workflows/_quickstart.yml
    with:
      product: ABTesting
      setup_command: scripts/setup_quickstart.sh abtesting
      plist_src_path: scripts/gha-encrypted/qs-abtesting.plist.gpg
      plist_dst_path: quickstart-ios/abtesting/GoogleService-Info.plist
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}


  abtesting-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/_cocoapods.cron.yml
    with:
      product: FirebaseABTesting
      platforms: '[ "ios", "tvos", "macos" ]'
      flags: '[ "--use-static-frameworks" ]'
