name: sdk.core.extension

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseCoreExtension.podspec'
    - 'FirebaseCore/Extension/**'
    - '.github/workflows/sdk.core.extension.yml'
    - '.github/workflows/_common.yml'
    - '.github/workflows/_cocoapods.yml'
    - '.github/workflows/_cocoapods.cron.yml'
    - 'Gemfile*'
  schedule:
    # Run every day at 3am (PDT) / 6am (EDT) - cron uses UTC times
    - cron:  '0 10 * * *'

jobs:
  # Since `FirebaseCoreExtension` only contains headers, linting is sufficient for testing.
  pod_lib_lint:
    uses: ./.github/workflows/_cocoapods.yml
    with:
      product: FirebaseCoreExtension

  core-extension-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/_cocoapods.cron.yml
    with:
      product: FirebaseCoreExtension
      platforms: '[ "ios", "tvos", "macos" ]'
      flags: '[ "--use-static-frameworks" ]'
