name: sdk.core.internal

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseCoreInternal.podspec'
    - 'FirebaseCore/Internal/**'
    - '.github/workflows/sdk.core.internal.yml'
    - '.github/workflows/_common.yml'
    - '.github/workflows/_cocoapods.yml'
    - '.github/workflows/_catalyst.yml'
    - '.github/workflows/_cocoapods.cron.yml'
    - 'Gemfile*'
  schedule:
    # Run every day at 3am (PDT) / 6am (EDT) - cron uses UTC times
    - cron:  '0 10 * * *'

jobs:
  spm:
    uses: ./.github/workflows/_common.yml
    with:
      target: FirebaseCoreInternalTests

  catalyst:
    strategy:
      matrix:
        target: [FirebaseCoreInternal-Unit-Unit, FirebaseCoreInternal-Unit-Integration]
    uses: ./.github/workflows/_catalyst.yml
    with:
      product: FirebaseCoreInternal
      target: ${{ matrix.target }}

  pod_lib_lint:
    uses: ./.github/workflows/_cocoapods.yml
    with:
      product: FirebaseCoreInternal
      supports_swift6: true

  core-internal-cron-only:
    needs: pod_lib_lint
    uses: ./.github/workflows/_cocoapods.cron.yml
    with:
      product: FirebaseCoreInternal
      platforms: '[ "ios", "tvos", "macos" ]'
      flags: '[ "--use-static-frameworks" ]'
