name: release

on:
  pull_request:
    paths:
    - '.github/workflows/update_specstaging.yml'
    - '.github/*'

jobs:

  quickstart_release_test:
    # Don't run on private repo unless it is a PR.
    # if: github.repository != 'FirebasePrivate/firebase-ios-sdk' || github.event_name == 'pull_request'
    env:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
      signin_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: SpecStaging Repo clone
      run: |
        if [ -f "${HOME}/.cocoapods/repos" ]; then
          find  "${HOME}/.cocoapods/repos" -type d -maxdepth 1 -exec sh -c 'pod repo remove $(basename {})' \;
        fi
        pod repo add specstaging https://github.com/firebase/SpecsStaging.git
        SPEC_REPO="specstaging" scripts/add_podspecs.swift
