name: watchos-sample

on:
  pull_request:
    paths:
    # Sources
    - 'FirebaseABTesting/**'
    - 'FirebaseDatabase/**'
    - 'FirebaseRemoteConfig/**'
    - 'FirebaseStorageInternal/**'
    # Sample
    - 'Example/watchOSSample/**'
    # Firebase Podspec
    - 'Firebase.podspec'
    # This file
    - '.github/workflows/watchos-sample.yml'
    # Rebuild on Ruby infrastructure changes
    - 'Gemfile*'
  schedule:
    # Run every day at 10pm (PST) - cron uses UTC times
    - cron:  '0 6 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  watchos-sample-build-test:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: mikehardy/buildcache-action@50738c6c77de7f34e66b870e4f8ede333b69d077
      with:
        cache_key: ${{ matrix.os }}
    - uses: ruby/setup-ruby@v1
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Prereqs
      run: scripts/install_prereqs.sh WatchOSSample watchOS
    - name: Build
      run: ([ -z $plist_secret ] || scripts/build.sh WatchOSSample watchOS)
